name: Check and test
'on':
  - push
  - pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        working-directory: py
        run: |
          pip install -r requirements.txt -r requirements-check.txt -r requirements-test.txt
      - name: Install Node.js dependencies
        working-directory: js
        run: npm install
      - name: Run checks
        working-directory: sh
        run: ./check_code.sh
      - name: Run Python tests
        working-directory: py
        run: pytest

